### ISSUE TITLE
Структура папки DocLister

### ISSUE THREAD

**Issue by Aharito** [evolution-cms/docs#27]
Планирую скоро добавить описание DLBuildMenu сюда.

Вопросы:
1. Как лучше расположить по структуре? если просто в "Сниппетах", то будет мешанина. Думаю. логичнее будет сделать подпапку типа "Сниппеты из комплекта DocLister", только название надо покороче придумать.

2. Написание, а особенно оформление доков - дело муторное и долгое. Кто писал, тот знает :)
В связи с этим вопрос - будет ли уместно под доками разместить ссылку на свой сайт типа Автор документации: Aharito? чтобы был хоть какой-то бонус за работу. Или нежелательно?

**Comment by dmi3yy** [comment]
Пиши сниппеты DocLister

Да ссылки вставляй если надо без проблем  я по этому поводу не заморачиваюсь;)


Отправлено с iPhone
